### ISSUE TITLE
README

### ISSUE THREAD

**Issue by xinyuanyu** [gmfe/react-mgm#12]
http://localhost:4000 instead of http://localhost:4000/demo/ is available in my computer after npm starting.

**Comment by liyatang** [comment]
奇怪！！！从目录层级来看 /demo 比较合理哦？
![image](https://cloud.githubusercontent.com/assets/1010130/14948886/a29b14fc-1077-11e6-9eb5-e137210d7c58.png)
![image](https://cloud.githubusercontent.com/assets/1010130/14948897/bbaefd82-1077-11e6-93f7-675615dfa85c.png)

**Comment by xinyuanyu** [comment]
我看了下可能是我那边clone的版本对不上，index.html之类的已经移动到demo中就应该没问题了

**Comment by liyatang** [comment]
Thank you for your interest
